---
title: "Curriculum Vitae"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Academic and Hospital Appointments

**Assistant Professor of Anesthesiology**  
Columbia University Irving Medical Center, New York, NY  
02/2019 - present	 


**Assistant Attending**  
New York-Presbyterian Hospital, New York, NY  
02/2019 - present  

## Education
**Patient Oriented Research, Master of Science degree program**  
Columbia University Mailman School of Public Health, New York, NY  
09/2018 - present	(expected completion May 2020)


**Certificate, Columbia Summer Research Institute** 
Columbia University Mailman School of Public Health, New York, NY  
Five week intensive summer program including courses in biostatistics, epidemiology, and research design for clinical and translational research.  
07/2018 - 08/2018	


**Doctor of Medicine**   
Albert Einstein College of Medicine, Bronx, NY  
07/2005 - 05/2013	 


**Doctor of Philosophy**  
Albert Einstein College of Medicine, Bronx, NY  
Thesis: Structure-function analysis of KCNQ1 and KCNE1 C-terminal interactions. Advisor: Thomas V. McDonald  
07/2005 - 05/2013	


**Master of Science**  
Albert Einstein College of Medicine, Bronx, NY  
07/2005 - 06/2009	 


**Bachelor of Arts** Magna Cum Laude with Honors in the Major (Neuroscience)  
Wellesley College, Wellesley, MA  
08/2001 - 06/2005	 


## Training
**Postdoctoral Research Fellow**  
Department of Anesthesiology  
Columbia University Irving Medical Center, New York, NY  
08/2018 – 01/2019 	


**Fellow, Division of Pediatric Anesthesiology**  
Department of Anesthesiology, Columbia University Medical Center  
New York-Presbyterian Morgan Stanley Children’s Hospital, New York, NY  
08/2017 – 07/2018 	


**Chief Resident, Department of Anesthesiology**  
Columbia University Medical Center  
New York-Presbyterian Hospital, New York, NY  
07/2016 – 06/2017	 


**Resident, Department of Anesthesiology**  
New York-Presbyterian Hospital, New York, NY  
07/2013 – 06/2017	 


