---
title: "Exploring Instacart Data"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)
data("instacart")
```

##  How Many Items Are Ordered From Each Aisle?
```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n, .desc = FALSE)) %>% 
  plot_ly(
    x = ~aisle,
    y = ~n,
    color = ~aisle,
    type = "bar"
  ) %>% 
  layout(yaxis = list(title = "Number of Items")) %>% 
  layout(xaxis = list(title = "Aisle")) %>% 
  layout(title = "Number of Items Ordered From each Aisle")
```

## Is There A Correlation Between Order Day of Week and Days Since Prior Order?
```{r}
instacart %>% 
  select(order_id, order_dow, order_hour_of_day, days_since_prior_order) %>% 
  distinct() %>% 
  mutate(order_dow = case_when(
      order_dow == "0" ~ "Sunday",
      order_dow == "1" ~ "Monday",
      order_dow == "2" ~ "Tuesday",
      order_dow == "3" ~ "Wednesday",
      order_dow == "4" ~ "Thursday",
      order_dow == "5" ~ "Friday",
      order_dow == "6" ~ "Saturday")
    ) %>% 
  group_by(order_dow) %>% 
  summarize(avg_days = mean(days_since_prior_order)) %>% 
  mutate(forcats::fct_reorder(order_dow, c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))) %>% 
  plot_ly(
    x = ~order_dow,
    y = ~avg_days,
    type = "scatter", 
    mode = "markers") %>% 
  layout(yaxis = list(title = "Average Number of Days Since Last Order")) %>% 
  layout(xaxis = list(title = "Day of Week")) %>% 
  layout(title = "Relationship Between Order Day of Week and Number Of Days Since Last Order")
```

## What's the average time of ordering for the 10 most popular items?

```{r}
# Figure out 10 most popular items
most_popular_10 = instacart %>% 
  count(product_name, sort = TRUE) %>% 
  top_n(10)

instacart %>% 
  filter(product_name %in% c("Bag of Organic Bananas", "Banana", "Large Lemon", "Limes", "Organic Avocado", "Organic Baby Spinach", "Organic Hass Avocado", "Organic Raspberries", "Organic Strawberries", "Strawberries")) %>% 
  select(product_name, order_hour_of_day) %>% 
  plot_ly(
    y = ~order_hour_of_day, 
    color = ~product_name, 
    type = "box",
    colors = "Set2") %>% 
  layout(yaxis = list(title = "Hour of the Day")) %>% 
  layout(title = "Distribution of Ordering Time for the 10 Most Popular Items")
```

