---
title: "NYC Restaurant Inspection Data"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)
```

```{r}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 
```
## Top 5 Most Popular Ethnic Cuisines in Manhattan
```{r}
popular_manhattan = nyc_inspections %>% 
  rename(id = camis, restaurant_name = dba) %>% 
  select(id, restaurant_name, boro, cuisine_description, latitude, longitude) %>% 
  filter(
    boro == "Manhattan") %>% 
  distinct()
```

```{r}
popular_manhattan %>% 
  select(id, cuisine_description) %>% 
  group_by(cuisine_description) %>% 
  summarise(cuisine_count = n()) %>% 
  arrange(-cuisine_count)
```

```{r}
popular_manhattan %>% 
  filter(cuisine_description %in% c("Italian", "Chinese", "Japanese", "Mexican", "French")) %>% 
  plot_ly(
    x = ~longitude, 
    y = ~latitude, 
    type = "scatter", 
    mode = "markers", 
    color = ~cuisine_description,
    text = ~restaurant_name,
    alpha = 0.5) %>% 
    layout(xaxis = list(autorange = "reversed"))
```

## Manhattan Chinese Restaurant Grades
```{r}
manhattan_chinese = nyc_inspections %>% 
  rename(id = camis, restaurant_name = dba) %>% 
  select(id, restaurant_name, boro, zipcode, cuisine_description, grade, latitude, longitude) %>% 
  filter(
    boro == "Manhattan",
    cuisine_description == "Chinese",
    !is.na(grade)) %>% 
  distinct()
```

```{r}
manhattan_chinese %>% 
  mutate(text_label = str_c(restaurant_name, "Grade:",grade, sep = "<br />")) %>% 
  plot_ly(
    x = ~longitude, 
    y = ~latitude, 
    type = "scatter", 
    mode = "markers", 
    color = ~grade,
    text = ~text_label,
    alpha = 0.5) %>% 
  layout(xaxis = list(autorange = "reversed"))
```


## Manhattan Restaurants Average Score by Zip Code
```{r}
nyc_inspections %>% 
  rename(id = camis, restaurant_name = dba) %>% 
  select(id, restaurant_name, boro, cuisine_description, zipcode, score) %>% 
  filter(
    boro == "Manhattan",
    !is.na(score))
```

  
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
